### PR TITLE
White and transparent notify icons

### PR DESCRIPTION
**Pull request by AlexeyBarabash**
This is a fix for https://github.com/brave/browser-android-tabs/issues/484 .

### CODE REVIEW

**Comment by AlexeyBarabash** [comment]
This is how it looks on devices

Android 4.1:
screenshot_2017-12-18-14-28-22
screenshot_2017-12-18-14-28-29

Androi 7.1
screenshot_20171218-142408
screenshot_20171218-142449
screenshot_20171218-143224

**Comment by jamesmudgett** [comment]
Looks very nice. Only one that I think should changes is when brave is on a lighter background in the settings menu. It should not be inverted, instead use the cutout version of the logo, attached.
brave-cutout

**Comment by AlexeyBarabash** [comment]
Unfortunately, we cannot use different icons for status bar and pulled down notification area. The requirements for notification icon is to have only white and transparent colors. The icon is inverted by the system when notification bar is pulled down. It is possible to set the accent color as only allowed customization, then the icon is not inverted, but white is replaced with an accent color in notification bar only. Will try to use accent color and update PR then.

**Comment by AlexeyBarabash** [comment]
@jamesmudgett ,
Not a beautiful inverted icon appears only in notification drawer area on Android 7 and 8 only. In earlier versions the Lion's image is not inverted and looks good.
screenshot from 2017-12-28 15-30-37-a5 0
screenshot from 2017-12-28 15-31-57a6 0


Android API does not provide ability to set a different icons for the notification area and the drawer. It allows only to specify an accent color for the icon which replaces the white color on the original icon. This does not helps for the current situation, but can make it lighter.
screenshot from 2017-12-28 16-30-17a8 1


The only way how to put a separate icon into the notification drawer is to use custom layout.
screenshot from 2017-12-28 16-55-02-custom8 1

This approach has a big disadvantage: each Android OS version has own different standard layouts, plus hardware vendors also can customize the layouts. So such custom layout will be noticeably different from the overall style of the system. Also some compatibity issues are possible with different device models.

The perfect way would be to have a one-colored icon which looks good both in normal and inverted versions. Such approach is done for all standard Android applications (Chrome, Alarm, Play Market, Google Maps).
In the current Brave icon the white color is used for specifying Lion's face and the dark is used to specify Lion's hair. But to make the image look good both in the normal and inverted states, the color should depict the shape of a simple object, so it is unclear how to make Brave's logo in a such way.

So there are three options, I think:
1) keep as is;
2) the same as pt. 1, but make it colored;
3) make the icon which looks good in a normal and in an inverted states.

@jamesmudgett, do you have any thoughts on this?

**Pull request merged**
