### PR TITLE
Translate Exit into right chinese word 退出

### PR DESCRIPTION
**Pull request by netroby**
Signed-off-by: ZhiFeng Hu <hufeng1987@gmail.com>

### CODE REVIEW

**Comment by netroby** [comment]
@SergeyZhukovsky Have a look?

**Comment by SergeyZhukovsky** [comment]
Hi @netroby, thank you very much for you PR. Is it the same word for Japanese as well?

**Comment by netroby** [comment]
In japanese， The full words may like : 退出します 
short called can be 退出

**Comment by netroby** [comment]
You can copy words in http://www.excite.co.jp/world/chinese/
This is a japanese translate engine.

**Comment by SergeyZhukovsky** [comment]
Ok, got it, thanks, merged it!

**Comment by netroby** [comment]
thanks




On Thu, Feb 9, 2017 at 9:55 PM +0800, "Serg" <notifications@github.com> wrote:












Ok, got it, thanks, merged it!

**Pull request merged**
