### PR TITLE
Limit same time ads. Issue # 1932

### PR DESCRIPTION
**Pull request by gdregalo**
Resolves issue# 1932.
Works together with PR into `brave-core`: https://github.com/brave/brave-core/pull/3306.
(branches: limit_same_time_ads->android_76v2).
Also, it handles:
1. notifications dismiss event when browser is off;
2. closes notifications from `bat-native-ads` service between sessions.

### CODE REVIEW

**Comment by tmancey** [comment]
This solution changes Chromium code that will affect all platforms. If we need to change Chromium code we need to create a patch, however we should be looking at a solution in the brave layer

**Comment by gdregalo** [comment]
@tmancey 
This is how Android browser is built so far.  We work with the code directly in `browser-android-tabs`  repo.

**Comment by bridiver** [comment]
I'm trying to wrap my head around why this was done in the notification display service instead of the ads service. Can someone explain it to me?

**Comment by gdregalo** [comment]
I can explain. 
There were changes applied to ads service as well (see PR description).
There was a problem when a browser  is closed and notification is tapped/closed and the event about it didn't reach ads service. This PR fixes the problem.

**Comment by gdregalo** [comment]
This code has a problem with web-notifications which was resolved later in:
https://github.com/brave/browser-android-tabs/pull/2271

**Pull request merged**
