### PR TITLE
search suggestions turned off by default, use top 500 Alexa sites

### PR DESCRIPTION
**Pull request by AlexeyBarabash**
This is change for https://github.com/brave/browser-android-tabs/issues/445 .

### CODE REVIEW

**Comment by AlexeyBarabash** [comment]
Sounds good. Made a build https://github.com/brave/browser-android-tabs/releases/tag/v1.0.38(beta1)  for QA team.

**Comment by SergeyZhukovsky** [comment]
It is tested already and works well. @samartnik could you please review it, so we can merge to master?

**Comment by AlexeyBarabash** [comment]
Fixed bug of upgrade found by QA https://github.com/brave/browser-android-tabs/issues/445#issuecomment-345010006 .

**Comment by AlexeyBarabash** [comment]
@SergeyZhukovsky , @samartnik , could you please review https://github.com/brave/browser-android-tabs/pull/460/commits/05d1f64b9a5e4923a7ddaab698d9f79268f69836 ?

**Comment by samartnik** [comment]
++

**Pull request merged**
