### PR TITLE
open YouTube links in Brave

### PR DESCRIPTION
**Pull request by AlexeyBarabash**
This is fix for https://github.com/brave/browser-android-tabs/issues/497 .

### CODE REVIEW

**Comment by SergeyZhukovsky** [comment]
++ on the change. Could you please make an option for that?

**Comment by AlexeyBarabash** [comment]
Made it as an option.
Default value is 'disabled'.
@jamesmudgett , could you please review icons and strings at https://github.com/brave/browser-android-tabs/pull/508/files#diff-543312251cada1b8ce4f9fb2b8a5cf1dR3492 ?

screenshot_20180112-185712
screenshot_20180112-185706

**Comment by jamesmudgett** [comment]
Lets change text to "Launch YouTube videos in Brave", also change "Video in background" to "Background video playback"

For "Launch YouTube videos in Brave" details: If enabled, videos will be played in Brave instead of YouTube app.

**Comment by AlexeyBarabash** [comment]
Updated PR with fixes for @jamesmudgett notices

**Comment by AlexeyBarabash** [comment]
Updated PR with new strings and icons.
screenshot_20180116-223056
screenshot_20180116-223039

**Comment by jamesmudgett** [comment]
Lets rename "Keep playing video in Brave" to "Video playback in Brave"

**Comment by AlexeyBarabash** [comment]
Fixed strings to "Video playback in Brave".
screenshot_20180117-102238
screenshot_20180117-102232

**Pull request merged**
